-- AlterTable
ALTER TABLE "Mahasiswa" ALTER COLUMN "jumlah_sks" DROP DEFAULT,
ALTER COLUMN "jumlah_sks" SET DATA TYPE TEXT,
ALTER COLUMN "ipk" DROP DEFAULT,
ALTER COLUMN "ipk" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "MataKuliah" ALTER COLUMN "sks" SET DATA TYPE TEXT;
